version: '3.3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "blobDB"
      POSTGRES_USER: "max"
      POSTGRES_PASSWORD: "pass"
    ports:
      - '5432:5432'


#docker exec -it <id> bash
#psql -U max -d blobDB